/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 phone.gltf --transform
Author: iSteven (https://sketchfab.com/OneSteven)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-pro-c14aa19d45674948bda936d9d3de744b
Title: iPhone 14 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/phone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_aple_0.geometry} material={materials.aple} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh001_buton_0.geometry} material={materials.buton} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh002___FUNDO_SIN_CARD_21_0.geometry} material={materials.FUNDO_SIN_CARD_21} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh003_frame_0.geometry} material={materials.frame} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh007_screen_0.geometry} material={materials.screen} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh009_cam_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh010_ring_0.geometry} material={materials.ring} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh013_black_0.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh015_glass_0.geometry} material={materials.glass} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh016_flash_0.geometry} material={materials.flash} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh017_glass_flash_0.geometry} material={materials.glass_flash} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh018_back_0.geometry} material={materials.back} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh019_bl_0.geometry} material={materials.material_12} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh020_island_0.geometry} material={materials.island} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh022_back_gl_0.geometry} material={materials.back_gl} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/phone-transformed.glb')
